import type { QuizStep } from "./types";

export const steps: QuizStep[] = [
  {
    id: "ajuda",
    emoji: "💡",
    title: "Como podemos ajudar você hoje?",
    description: "Selecione uma ou mais opções. Você também pode escrever sua situação no campo abaixo.",
    fields: [
      {
        id: "necessidades",
        type: "checkbox",
        label: "Selecione o que deseja para sua família",
        options: [
          { value: "professor", label: "Professor Auxiliar", emoji: "👩‍🏫" },
          { value: "terapia", label: "Terapia", emoji: "🧠" },
          { value: "oculos", label: "Óculos até 2 graus", emoji: "👓" },
          { value: "municipio", label: "Auxílio no município", emoji: "🏛️" },
          { value: "documentos", label: "Ajuda com documentos", emoji: "📄" },
          { value: "transporte", label: "Transporte", emoji: "🚌" },
          { value: "saude", label: "Saúde", emoji: "🏥" },
          { value: "educacao", label: "Educação", emoji: "📚" },
          { value: "direitos", label: "Direitos PcD", emoji: "♿" },
          { value: "inclusao", label: "Inclusão escolar", emoji: "🧩" },
          { value: "emprego", label: "Emprego", emoji: "💼" },
          { value: "sociais", label: "Benefícios sociais", emoji: "🍽️" },
        ],
      },
      {
        id: "descricaoAjuda",
        type: "textarea",
        label: "✍️ Descreva como podemos ajudar você",
        placeholder: "Escreva aqui sua necessidade, dificuldade ou situação atual…",
      },
    ],
  },
  {
    id: "identificacao",
    emoji: "👤",
    title: "Sobre a Pessoa",
    description: "Conte um pouquinho sobre quem vamos acolher.",
    encouragement: "💙 Obrigado por continuar. Vamos com calma.",
    fields: [
      { id: "nomePaciente", type: "text", label: "Nome completo do PcD/TEA", required: true },
      { id: "cpfPaciente", type: "text", label: "CPF do PcD/TEA", required: true, placeholder: "000.000.000-00" },
      { id: "nomeResponsavel", type: "text", label: "Nome do responsável", required: true },
      { id: "cpfResponsavel", type: "text", label: "CPF do responsável", required: true, placeholder: "000.000.000-00" },
      { id: "nascimento", type: "date", label: "Data de nascimento" },
      { id: "idade", type: "number", label: "Idade" },
      { id: "telefone1", type: "tel", label: "Telefone principal", required: true },
      { id: "telefone2", type: "tel", label: "Telefone secundário" },
      { id: "email", type: "email", label: "E-mail" },
      { id: "endereco", type: "text", label: "Endereço completo" },
      { id: "bairro", type: "text", label: "Bairro" },
      { id: "cidade", type: "text", label: "Cidade" },
    ],
  },
  {
    id: "diagnostico",
    emoji: "🧩",
    title: "Informações sobre o Diagnóstico",
    description: "Se ainda não tiver diagnóstico fechado, tudo bem — escolha 'Em investigação'.",
    encouragement: "🌟 Suas respostas são muito importantes.",
    fields: [
      {
        id: "temDiagnostico",
        type: "radio",
        label: "Possui diagnóstico fechado?",
        options: [
          { value: "sim", label: "Sim", emoji: "✅" },
          { value: "nao", label: "Não", emoji: "❌" },
          { value: "investigacao", label: "Em investigação", emoji: "🔎" },
        ],
      },
      {
        id: "diagnosticos",
        type: "checkbox",
        label: "Qual diagnóstico?",
        options: [
          { value: "tea", label: "TEA", emoji: "🧩" },
          { value: "tdah", label: "TDAH", emoji: "⚡" },
          { value: "tod", label: "TOD", emoji: "🔶" },
          { value: "intelectual", label: "Deficiência Intelectual", emoji: "🧠" },
          { value: "genetica", label: "Síndrome genética", emoji: "🧬" },
          { value: "fisica", label: "Deficiência Física", emoji: "♿" },
          { value: "paralisia", label: "Paralisia Cerebral", emoji: "💚" },
          { value: "down", label: "Síndrome de Down", emoji: "💛" },
          { value: "sensorial", label: "Transtorno Sensorial", emoji: "🌈" },
          { value: "visual", label: "Deficiência Visual", emoji: "👁️" },
          { value: "auditiva", label: "Deficiência Auditiva", emoji: "👂" },
          { value: "altas", label: "Altas Habilidades", emoji: "✨" },
          { value: "outro", label: "Outro", emoji: "➕" },
        ],
      },
      { id: "diagnosticoOutro", type: "text", label: "Qual outro diagnóstico?", placeholder: "Descreva aqui…" },
    ],
  },
  {
    id: "suporte",
    emoji: "📊",
    title: "Nível de Suporte",
    description: "Essas informações ajudam a entender o tipo de apoio necessário.",
    encouragement: "🤝 Estamos construindo algo maior juntos.",
    fields: [
      {
        id: "nivelSuporte",
        type: "radio",
        label: "Nível de suporte",
        options: [
          { value: "1", label: "Nível 1", emoji: "1️⃣" },
          { value: "2", label: "Nível 2", emoji: "2️⃣" },
          { value: "3", label: "Nível 3", emoji: "3️⃣" },
          { value: "naosei", label: "Não sabe informar", emoji: "❔" },
        ],
      },
      { id: "laudo", type: "radio", label: "Possui laudo?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Ainda não", emoji: "❌" }] },
      { id: "ciptea", type: "radio", label: "Possui CIPTEA?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Ainda não", emoji: "❌" }] },
      { id: "carteirinha", type: "radio", label: "Possui Carteira PcD?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Ainda não", emoji: "❌" }] },
    ],
  },
  {
    id: "dificuldades",
    emoji: "⚠️",
    title: "Dificuldades do Dia a Dia",
    description: "Marque tudo que faz parte da rotina de vocês. Não precisa marcar todas.",
    encouragement: "🧩 Cada informação ajuda outras famílias.",
    fields: [
      {
        id: "motora",
        type: "checkbox",
        label: "Coordenação Motora",
        options: [
          { value: "lapis", label: "Segurar lápis", emoji: "✏️" },
          { value: "escrever", label: "Escrever", emoji: "📝" },
          { value: "recortar", label: "Recortar", emoji: "✂️" },
          { value: "ampla", label: "Coordenação ampla", emoji: "🤸" },
          { value: "equilibrio", label: "Equilíbrio", emoji: "⚖️" },
        ],
      },
      {
        id: "autonomia",
        type: "checkbox",
        label: "Autonomia",
        options: [
          { value: "vestir", label: "Vestir roupa", emoji: "👕" },
          { value: "escovar", label: "Escovar dentes", emoji: "🪥" },
          { value: "comer", label: "Comer sozinho", emoji: "🍽️" },
          { value: "banho", label: "Tomar banho", emoji: "🛁" },
          { value: "desfralde", label: "Desfralde", emoji: "🚼" },
        ],
      },
      {
        id: "sensorial",
        type: "checkbox",
        label: "Sensorial",
        options: [
          { value: "som", label: "Hipersensibilidade sonora", emoji: "🔊" },
          { value: "alimentar", label: "Seletividade alimentar", emoji: "🍎" },
          { value: "toque", label: "Sensibilidade ao toque", emoji: "🤲" },
          { value: "busca", label: "Busca sensorial", emoji: "🌀" },
          { value: "crises", label: "Crises sensoriais", emoji: "⚡" },
        ],
      },
      {
        id: "social",
        type: "checkbox",
        label: "Social e Comportamental",
        options: [
          { value: "comunicacao", label: "Comunicação", emoji: "💬" },
          { value: "interacao", label: "Interação social", emoji: "🤝" },
          { value: "rigidez", label: "Rigidez comportamental", emoji: "🔁" },
          { value: "agressividade", label: "Agressividade", emoji: "⚠️" },
          { value: "auto", label: "Autoagressão", emoji: "🆘" },
          { value: "fuga", label: "Fuga/perigo", emoji: "🏃" },
        ],
      },
    ],
  },
  {
    id: "educacao",
    emoji: "📚",
    title: "Educação e Inclusão",
    description: "Como está a vida escolar?",
    encouragement: "✨ Você está ajudando a transformar vidas.",
    fields: [
      { id: "estuda", type: "radio", label: "Estuda atualmente?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Não", emoji: "❌" }] },
      { id: "tipoEscola", type: "radio", label: "Tipo de escola", options: [{ value: "publica", label: "Pública", emoji: "🏫" }, { value: "particular", label: "Particular", emoji: "🏛️" }] },
      { id: "at", type: "radio", label: "Possui acompanhante terapêutico?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Não", emoji: "❌" }] },
      { id: "dificuldadeEscolar", type: "radio", label: "Já houve dificuldade escolar?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Não", emoji: "❌" }] },
      { id: "semEscola", type: "radio", label: "Está sem escola no momento?", options: [{ value: "sim", label: "Sim", emoji: "⚠️" }, { value: "nao", label: "Não", emoji: "✅" }] },
      { id: "frequencia", type: "radio", label: "Frequência reduzida?", options: [{ value: "sim", label: "Sim", emoji: "⚠️" }, { value: "nao", label: "Não", emoji: "✅" }] },
    ],
  },
  {
    id: "tratamentos",
    emoji: "🩺",
    title: "Tratamentos e Terapias",
    description: "Marque as terapias que já fazem parte da rotina.",
    fields: [
      {
        id: "terapias",
        type: "checkbox",
        label: "Terapias atuais",
        options: [
          { value: "psico", label: "Psicóloga", emoji: "💭" },
          { value: "fono", label: "Fonoaudióloga", emoji: "🗣️" },
          { value: "to", label: "TO", emoji: "✋" },
          { value: "psicop", label: "Psicopedagoga", emoji: "📖" },
          { value: "neuro", label: "Neurologista", emoji: "🧠" },
          { value: "psiquiatra", label: "Psiquiatra", emoji: "💊" },
          { value: "fisio", label: "Fisioterapia", emoji: "🤸" },
          { value: "aba", label: "ABA", emoji: "🎯" },
          { value: "outro", label: "Outro", emoji: "➕" },
        ],
      },
      { id: "filaSus", type: "radio", label: "Está na fila do SUS?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Não", emoji: "❌" }] },
      { id: "tempoEspera", type: "text", label: "Há quanto tempo espera atendimento?", placeholder: "Ex.: 6 meses, 2 anos…" },
    ],
  },
  {
    id: "familia",
    emoji: "🏠",
    title: "Situação Familiar",
    description: "Essas perguntas nos ajudam a entender o contexto da família.",
    encouragement: "💙 Você está quase lá.",
    fields: [
      { id: "moradores", type: "number", label: "Quantas pessoas moram na casa?" },
      { id: "renda", type: "text", label: "Renda familiar aproximada", placeholder: "Ex.: 1 salário mínimo" },
      { id: "trabalha", type: "radio", label: "Responsável consegue trabalhar?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "parcial", label: "Parcialmente", emoji: "🌗" }, { value: "nao", label: "Não", emoji: "❌" }] },
      { id: "bpc", type: "radio", label: "Recebe BPC/LOAS?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Não", emoji: "❌" }, { value: "solicitado", label: "Já solicitou", emoji: "📝" }, { value: "negado", label: "Tentei e foi negado", emoji: "🚫" }] },
      { id: "gastosTerapia", type: "radio", label: "Há gastos elevados com terapias?", options: [{ value: "sim", label: "Sim", emoji: "✅" }, { value: "nao", label: "Não", emoji: "❌" }] },
    ],
  },
  {
    id: "urgencia",
    emoji: "🚨",
    title: "Situação Atual",
    description: "Estamos quase no fim. Conte com calma o que está acontecendo agora.",
    fields: [
      { id: "porqueImportante", type: "textarea", label: "Por que essa vaga é importante neste momento?", placeholder: "Compartilhe com suas palavras…" },
      {
        id: "urgenciaSituacao",
        type: "checkbox",
        label: "Marque o que se aplica",
        options: [
          { value: "regressao", label: "Risco de regressão", emoji: "📉" },
          { value: "semTerapia", label: "Sem terapia", emoji: "🚫" },
          { value: "crises", label: "Crises intensas", emoji: "⚡" },
          { value: "exclusao", label: "Exclusão escolar", emoji: "🏫" },
          { value: "sobrecarga", label: "Sobrecarga extrema do cuidador", emoji: "🫂" },
          { value: "outro", label: "Outro", emoji: "➕" },
        ],
      },
    ],
  },
  {
    id: "direitos",
    emoji: "📜",
    title: "Direitos e Benefícios",
    description: "Marque o que vocês já conhecem, recebem ou gostariam de saber mais.",
    encouragement: "🌟 Última etapa! Você é incrível.",
    fields: [
      {
        id: "saude",
        type: "checkbox",
        label: "🩺 Saúde",
        options: [
          { value: "sus", label: "Atendimento pelo SUS", emoji: "🏥" },
          { value: "medicamentos", label: "Medicamentos gratuitos", emoji: "💊" },
          { value: "passe", label: "Passe livre saúde", emoji: "🎟️" },
        ],
      },
      {
        id: "educacaoDir",
        type: "checkbox",
        label: "📚 Educação",
        options: [
          { value: "aee", label: "AEE (Atendimento Educacional Especializado)", emoji: "🎒" },
          { value: "professorApoio", label: "Professor de apoio", emoji: "👩‍🏫" },
          { value: "materialAdaptado", label: "Material adaptado", emoji: "📘" },
        ],
      },
      {
        id: "trabalho",
        type: "checkbox",
        label: "💼 Trabalho",
        options: [
          { value: "cotas", label: "Lei de cotas PcD", emoji: "📋" },
          { value: "aposentadoria", label: "Aposentadoria PcD", emoji: "🧓" },
        ],
      },
      {
        id: "transporteDir",
        type: "checkbox",
        label: "🚌 Transporte",
        options: [
          { value: "passeLivre", label: "Passe livre interestadual", emoji: "🚍" },
          { value: "municipal", label: "Transporte municipal gratuito", emoji: "🚐" },
          { value: "isencaoIpva", label: "Isenção de IPVA", emoji: "🚗" },
        ],
      },
      {
        id: "assistencia",
        type: "checkbox",
        label: "🤝 Assistência Social",
        options: [
          { value: "bpcLoas", label: "BPC/LOAS", emoji: "💵" },
          { value: "cras", label: "Acompanhamento CRAS/CREAS", emoji: "🏢" },
          { value: "cestaBasica", label: "Cesta básica", emoji: "🥫" },
        ],
      },
      {
        id: "previdencia",
        type: "checkbox",
        label: "🏛️ Previdência Social",
        options: [
          { value: "auxDoenca", label: "Auxílio doença", emoji: "📄" },
          { value: "pensao", label: "Pensão por invalidez", emoji: "📜" },
        ],
      },
      {
        id: "habitacao",
        type: "checkbox",
        label: "🏠 Habitação",
        options: [
          { value: "mcmv", label: "Minha Casa Minha Vida – cota PcD", emoji: "🏡" },
          { value: "adaptacao", label: "Adaptação da moradia", emoji: "🛠️" },
        ],
      },
      {
        id: "cultura",
        type: "checkbox",
        label: "🎭 Cultura e Lazer",
        options: [
          { value: "meiaEntrada", label: "Meia-entrada", emoji: "🎟️" },
          { value: "espacosAdaptados", label: "Espaços adaptados", emoji: "🎢" },
        ],
      },
      {
        id: "tributacao",
        type: "checkbox",
        label: "💰 Tributação",
        options: [
          { value: "isencaoIR", label: "Isenção de IR", emoji: "📑" },
          { value: "isencaoIpi", label: "Isenção de IPI/ICMS", emoji: "🧾" },
        ],
      },
      {
        id: "acessibilidade",
        type: "checkbox",
        label: "♿ Acessibilidade",
        options: [
          { value: "rampas", label: "Rampas e acessos", emoji: "🛤️" },
          { value: "tecnologia", label: "Tecnologia assistiva", emoji: "🦾" },
          { value: "cao", label: "Cão-guia", emoji: "🐕‍🦺" },
        ],
      },
    ],
  },
  {
    id: "consentimento",
    emoji: "🔒",
    title: "Privacidade e Termo",
    description: "Para finalizar, precisamos do seu aceite. Seus dados ficam seguros conosco.",
    fields: [
      {
        id: "aceiteLgpd",
        type: "consent",
        required: true,
        label:
          "Autorizo o uso das informações para cadastro interno, organização da fila de espera, elaboração de estatísticas da associação e mapeamento das necessidades das pessoas com deficiência do município, preservando a confidencialidade dos dados pessoais.",
      },
      {
        id: "aceiteTermo",
        type: "consent",
        required: true,
        label:
          "Estou ciente de que esta é uma pré-inscrição, com validade de até 12 meses, podendo haver atualização cadastral e critérios de priorização conforme avaliação técnica e social da associação.",
      },
    ],
  },
];