/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RespostasRouteImport } from './routes/respostas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartaoTokenRouteImport } from './routes/cartao.$token'

const RespostasRoute = RespostasRouteImport.update({
  id: '/respostas',
  path: '/respostas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartaoTokenRoute = CartaoTokenRouteImport.update({
  id: '/cartao/$token',
  path: '/cartao/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/respostas': typeof RespostasRoute
  '/cartao/$token': typeof CartaoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/respostas': typeof RespostasRoute
  '/cartao/$token': typeof CartaoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/respostas': typeof RespostasRoute
  '/cartao/$token': typeof CartaoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/respostas' | '/cartao/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/respostas' | '/cartao/$token'
  id: '__root__' | '/' | '/admin' | '/respostas' | '/cartao/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  RespostasRoute: typeof RespostasRoute
  CartaoTokenRoute: typeof CartaoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/respostas': {
      id: '/respostas'
      path: '/respostas'
      fullPath: '/respostas'
      preLoaderRoute: typeof RespostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cartao/$token': {
      id: '/cartao/$token'
      path: '/cartao/$token'
      fullPath: '/cartao/$token'
      preLoaderRoute: typeof CartaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  RespostasRoute: RespostasRoute,
  CartaoTokenRoute: CartaoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
